### ISSUE TITLE
Request: Multiple Sound Effect Support

### ISSUE THREAD

**Issue by SushiKishi** [typeou/karasubonk#5]
I know that by setting up a custom event, I can select multiple sound effects for that event. I can use that for a Channel Points redeem where someone redeems a Shuba Duck, throws a Shubaduck at me, and the bonk sound effect is randomly chosen from a handful of Shuba sound clips.

But that doesn't work for the Barrage events unless I add the same throwable multiple times and assign it each of the different sound effects.  If I wanted to do a custom Barrage event and allow, say, all the default fruits and their splats plus all the Shuba splats, I can't use the sound effect gallery in the custom events because the fruits will get Shuba Splats and vice-versa.

If adding multiple splat sounds to a single throwable isn't doable, a "duplicate throwable" button would be helpful.

I'm not sure if this would also be a concern or not, but while I was trying to figure out how to set up what I wanted, I ended up choosing the same sound effect twice and the second one got a '2' appended to it. The file name doesn't bother me, I'm just wondering if it's holding all this stuff in memory, including two copies of the same file, which would make duplicating emotes like I want suck up a ton of resources at some point.

**Comment by typeou** [comment]
I'll look into this when I have some time, it would definitely be useful for that situation.

KBonk does currently make duplicates in storage whenever you import something that already exists, mainly just to make sure nothing gets overwritten by accident. Pretty much just for a situation where two files happen to have the same name, but different contents. I'll also look into a more robust system that only makes a new copy if a file in that situation instead of just doing it by default if it detects any duplicate.

**Comment by typeou** [comment]
The most recent update now prevents duplicate files from being created if the contents are the same. However, adding multi-sound effect support for specific items would require a good bit of UI redesigning that I don't think I have the time for right now unfortunately. The workaround of duplicate items is more efficient now, at least, since they'll all point to the same file!
