### ISSUE TITLE
Request: "Custom IP" for Dual PC setups

### ISSUE THREAD

**Issue by SushiKishi** [typeou/karasubonk#7]
I have OBS running on my Stream PC and when I can, I have my game PC also handle VTS, so it would be running KBonk too.

By default, if I have KBonk, VTS on game PC, and OBS on stream PC, this is what happens on "initial setup":

\--KBonk gets stuck on "Connecting to Browser" even if OBS connects to the bonker.html file on the game PC (shared via network).

\--KBonk can only "connect to browser' if I open the file on the Game PC, like in Firefox.

\--KBonk connects to VTS just fine -- sometimes I have to auth the plugin what seems like four or five times, but that's been my experience with every plugin.

\--KBonk says it's ready, but when I test bonks, the model moves and the items appear in the Firefox window on my Game PC, but nothin' happens in the bonker.html browser in OBS on the Stream PC. No audio, no throwables, nothing. THe model does get bonked, of course, since that's all "local"

\=====

I was able to get this working by manually modifying bonker.js to replace the localhost with the IP address for my Game PC. If I do this, then the "initial setup" goes like this

\--Game-PC's KBonk can detect that Stream-PC's OBS has opened bonker.html.  KBonk flashes on the "Version Mismatch" screen for a little bit before either going to "Connecting to VTS"

\--I have to remove the plugin from VTS and add it in again; this is probably because the plugin isn't coming from "localhost" in this setup. 

\--Afterwards it seems to work as expected.

\=====

There's some other things I'll need to tweak on my end, that are definitely outside the scope of what you'd want to fuss with for KBonk development.  Since I'm grabbing VTS by NDI but bonker.html by browser source, I'm positive there's going to be a bit of a desync between bonks landing and the model recoiling. I can fix this manually in OBS using video filters, and I can't imagine you'd want to figure out how to let users "desync" bonker.html and the VTS plugin inside of KBonk as it could give users more headaches than it's worth for what's a niche feature. But being able to set the IP would let users who have a dual-PC setup and should have enough know-how to work around the issues have easier access to do so.

**Comment by typeou** [comment]
This is a good suggestion, I'll add it to my to-do list for next time I'm able to work on an update!

**Comment by typeou** [comment]
I've added this in the 1.23 update, but can't actually confirm whether or not it works properly since I don't have a dual PC setup to test properly. There's some restrictions due to the browser source-based nature of KBonk that might make this more difficult than I thought at a glance.

The browser source is what actually connects to the KBonk application and to VTube Studio, and browser pages aren't allowed to access files outside of their immediate directory for obvious security reasons. Because of this, the KBonk application actually creates a file in the browser source's directory with the ports and IP addresses it needs to connect to instead of the browser source reading those from the main data file directly. My concern is whether a browser source that's being used over a network connection will actually be able to read that file properly. If it does, everything should work fine. If not, then there's a problem.

If your manual workaround required you to hard-code the port into the bonker.js file, then this implementation probably won't work. If it was able to grab the ports from that file just file, then we should be all hunky-dory.

Please let me know if it works for you! Thank you for your feedback!
