### ISSUE TITLE
Attack Angle?

### ISSUE THREAD

**Issue by Awfulpie** [typeou/karasubonk#9]
It would be nice if we could set the attack angle for the items, for example that items can only be thrown from the right top corner or in general only from the right side and so on

**Comment by typeou** [comment]
This is already supported through the "Throw Angle (Min)" + "Throw Angle (Max)" settings in the global "Throws" section in the general settings, or through the "Settings Overrides" in Custom Bonks!

**Comment by Awfulpie** [comment]
i thought so too but i played around with the angles.. even when i set it to something like 40-50 or 160 to 180 it still comes from left and right, it just changes slightly the vector for me?

**Comment by typeou** [comment]
You're definitely right, sorry, it's been quite a while since I've dived into the details on how everything works. This seemed pretty easy to add, so I've got a working "Throw Direction" global & custom bonk setting now. I'll look around for a few more little things to package into an update and there should be a version with this added out some time later today!
